### ISSUE TITLE
Странное поведение языковых конструкций

### ISSUE THREAD

**Issue by AlexandrGordeev** [MindyPHP/Mindy_Template#9]
```
{% for i in range(0,20)%}
    {{ i }} {% if loop.last %}  last iterate{% endif %}
{% endfor %}
```

При рендере:
## 01234567891011121314151617181920last iterate    

```
{% for i in range(0,20)%}
    {{ i }}      {% if loop.last %}  last iterate{% endif %}
{% endfor %}
```

При рендере:
01234567891011121314151617181920last iterate

**Comment by AlexandrGordeev** [comment]
Если это фитча, то пользоваться условиями в атрибутах тегов теперь нельзя, так как строка склеивается.

**Comment by max107** [comment]
Смотри https://github.com/studio107/Mindy_Template/issues/5

Для того чтобы пустое место не удалялось используй `{%- ... -%}`
